server:
  port: 33453
  servlet:
    context-path: /ai
spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${langchain4j.api-key}
      model-name: qwen-flash
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${langchain4j.api-key}
      model-name: text-embedding-v4
  community:
    redis:
      host: ${redis.host}
      port: ${redis.port}




